project_id = "admin-panel-restaurant"

[api]
enabled = true
port = 54321
schemas = ["public", "app"]
extra_search_path = ["public", "extensions", "app"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.migrations]
enabled = true
schema_paths = []

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]

[functions]
enabled = true
verify_jwt = true
